GET localhost:8080/person
X-TenantID: user2

###

POST localhost:8080/person
Content-Type: application/json
X-TenantID: user2

{
  "name": "John2"
}

###

GET localhost:8181/person
X-TenantID: vmware

###

POST localhost:8181/person
Content-Type: application/json
X-TenantID: vmware

{
  "name": "Test VMWARE"
}